name: main

on:
  push:
    branches:
    - master

jobs:
  build-driver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Make
      working-directory: embedded-scd
      run: |
        make prepare
        make
        make clean
        make release

    - name: Build stub release driver
      working-directory: embedded-scd/release/scd30
      run: |
        make CONFIG_I2C_TYPE=hw_i2c
        make CONFIG_I2C_TYPE=sw_i2c
        make clean

    - name: Build Linux release drivers
      working-directory: embedded-scd/release/scd30
      run: |
        make CONFIG_I2C_TYPE=hw_i2c hw_i2c_impl_src=hw_i2c/sample-implementations/linux_user_space/sensirion_hw_i2c_implementation.c
        make CONFIG_I2C_TYPE=sw_i2c sw_i2c_impl_src=sw_i2c/sample-implementations/linux_user_space/sensirion_sw_i2c_implementation.c
        make clean

    - name: Upload driver artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: driver
        path: embedded-scd/release/scd30

  build-wasm:
    runs-on: ubuntu-latest
    container:
      image: trzeci/emscripten
    needs: [build-driver]
    steps:
      - name: Download driver artifact
        uses: actions/download-artifact@v1
        with:
          name: driver

      - name: Setup Emscripten
        run: |
          export OPTIMIZE="-Os"
          export LDFLAGS="${OPTIMIZE}"
          export CFLAGS="${OPTIMIZE}"
          export CXXFLAGS="${OPTIMIZE}"

      - name: Compiling wasm-scd30 bindings
        run: |
          emcc \
            ${OPTIMIZE} \
            --bind \
            -s STRICT=1 \
            -s ALLOW_MEMORY_GROWTH=1 \
            -s MALLOC=emmalloc \
            -s MODULARIZE=1 \
            -s EXPORT_ES6=1 \
            -s "EXTRA_EXPORTED_RUNTIME_METHODS=[\
              'scd30_read_measurement',\
              'scd30_get_data_ready',\
              'scd30_probe',\
              'scd30_get_driver_version',\
              'scd30_get_configured_address']" \
            -s "EXPORTED_FUNCTIONS=[\
              'scd30_start_periodic_measurement',\
              'scd30_stop_periodic_measurement',
              'scd30_read_serial',
              'scd30_set_measurement_interval',
              'scd30_get_data_ready',
              'scd30_set_temperature_offset',
              'scd30_set_altitude',
              'scd30_set_forced_recalibration',
              'scd30_enable_automatic_self_calibration']" \
            -o ./scd30.js \
             driver/scd30.c

      - name: Move artifacts
        run: |
          mkdir -p dist
          mv -t dist scd30.js scd30.wasm

      - name: Upload wasm-scd30 artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: wasm-scd30
          path: dist/

  build-package:
    runs-on: ubuntu-latest
    needs: [build-wasm]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install App Dependencies
        run: npm install --ignore-scripts

      - name: Download wasm-scd30 artifact
        uses: actions/download-artifact@v1
        with:
          name: wasm-scd30

      - name: Build
        run: npm run build

      - name: Move artifacts
        run: |
          mv -t dist package.json
          mv wasm-scd30 dist/modules/SCD30

      - name: Upload package artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: package
          path: dist/

  publish-npm:
    runs-on: ubuntu-latest
    needs: [build-package]
    steps:
      - name: Install npm modules
        run: npm install -g npm-cli-login

      - name: Npm CLI Login
        env:
          NPM_USER: ${{ secrets.USERNAME }}
          NPM_PASS: ${{ secrets.ACCESS_TOKEN }}
          NPM_EMAIL: ${{ secrets.EMAIL }}
          NPM_REGISTRY: https://npm.pkg.github.com/
        run: npm-cli-login

      - name: Download package artifact
        uses: actions/download-artifact@v1
        with:
          name: package

      - name: Publish package to GitHub Packages
        working-directory: package/
        run: npm publish

