name: main

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build driver
      run: npm run docker

    - name: Upload package artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: package
        path: dist/

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v1
        with:
          name: package

      - name: Run Test
        working-directory: package/
        run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Install npm modules
        run: npm install -g npm-cli-login

      - name: Npm CLI Login
        env:
          NPM_USER: ${{ secrets.USERNAME }}
          NPM_PASS: ${{ secrets.ACCESS_TOKEN }}
          NPM_EMAIL: ${{ secrets.EMAIL }}
          NPM_REGISTRY: https://npm.pkg.github.com/
        run: npm-cli-login

      - name: Download package artifact
        uses: actions/download-artifact@v1
        with:
          name: package

      - name: Publish package to GitHub Packages
        working-directory: package/
        run: npm publish

